[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' 'unsafe-inline' https: blob:; connect-src 'self' https:; frame-src 'self' https:; object-src 'none';"
